services:
  - type: web
    name: teeio
    env: docker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: teeio
          property: connectionString

  - type: cron
    name: teeio-worker
    env: docker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: teeio
          property: connectionString

    schedule: "*/10 * * * *"
    startCommand: /app/tee-io-worker

databases:
  name: teeio
  ipAllowList: []
