# Values formatted like "_env:ENV_VAR_NAME:default_value" can be overridden by the specified environment variable.
# See https://github.com/yesodweb/yesod/wiki/Configuration#overriding-configuration-values-with-environment-variables

static-dir:      "_env:STATIC_DIR:static"
host:            "_env:HOST:*4" # any IPv4 host
port:            "_env:PORT:3000"
approot:         "_env:APPROOT:http://localhost:3000"
ip-from-header:  "_env:IP_FROM_HEADER:false"
command-timeout: "_env:COMMAND_TIMEOUT:300"
s3-url:          "_env:S3_URL:https://s3.amazonaws.com/tee.io.development"
debug:           "_env:DEBUG:false"

database-url:       "_env:DATABASE_URL:postgres://teeio:teeio@localhost:5432/teeio"
database-pool-size: "_env:PGPOOLSIZE:10" # use conventional variable

# Optional values with the following production defaults.
# In development, they default to the inverse.
#
# reload-templates: false
# mutable-static: false
# skip-combining: false
